### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by ErikSchierboom** [cake-contrib/Cake.FileHelpers#10]
I would really like to use this addin from my Cake.CoreCLR project, however this is not possible at the moment. I would be happy to tried and create a PR to make it .NET Core compatible, but that would involve converting the projects to the new .NET SDK, which means that the `.csproj` files will change. Not only that, but they can then only be opened in Visual Studio 2017, although then can of course be run using the .NET CLI. Is this something you would be interested in?

**Comment by ErikSchierboom** [comment]
@Redth Sorry to bother you with this, but is there any plan to implement this?

**Comment by devlead** [comment]
@ErikSchierboom likely down to limited time currently, so probably up for grabs for anyone willing to take a stab at it.

**Comment by ErikSchierboom** [comment]
@devlead Ah okay. I might look into somewhere in the next couple of weeks.

**Comment by devlead** [comment]
@ErikSchierboom ok, ping back here if this is something you would want to tackle.

**Comment by Redth** [comment]
I'm not even sure what's required at this point to make my addins CoreCLR compatible... Let's discuss in gitter :)

**Comment by ErikSchierboom** [comment]
@Redth Sure, let's do that. I'm currently trying to get Cake.CoreCLR run on .NET Core 2.0, so I'm learning about how to do this type of conversion :)

**Comment by gep13** [comment]
@Redth if you don't have any objections, I would like to suggest switching this repository to use Cake.Recipe, which already has support for building/publishing .net core solutions, and then it should be a small matter of upgrading the solution to latest 2017 tooling.

Thoughts?

**Comment by ErikSchierboom** [comment]
I've just made the first step in supporting .NET Core: update to the latest project format in #13 .

**Comment by Redth** [comment]
One thing I want to be mindful of is that I want all of my addins to still be able to be developed from Visual Studio for Mac.  Unfortunately that means as of right now `<TargetFrameworks>` is not well supported in .csproj.  This means if we want to target `netstandard1.6` and still also target `net45` we'll need to create another .csproj for it (and perhaps a shared project for the actual code implementation.  

`<PackageReference .. />` should mostly work fine in the .csproj already in Visual Studio for Mac, so these changes are good so far.

**Comment by ErikSchierboom** [comment]
@Redth Okay, thanks for the heads-up. I'll keep that in mind. Perhaps #13 could already be merged then, or should I just build on that PR?

**Comment by git-man** [comment]
First thank you all for your great work. 

Due to https://github.com/cake-build/cake/issues/2011 I managed to get .NET Core support by building this project on my own by changing the csproj to the following:

`
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Cake.Compression</RootNamespace>
    <AssemblyName>Cake.Compression</AssemblyName>
    <TargetFramework>netstandard2.0</TargetFramework>
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>
  <ItemGroup>
	 <PackageReference Include="Cake.Core" Version="0.26.1" />
	 <PackageReference Include="Cake.Common" Version="0.26.1"/>
	 <PackageReference Include="SharpZipLib" Version="1.0.0-alpha2" />
  </ItemGroup>
</Project>
`

Maybe you could incorporate it and bundle a release?

**Comment by nmbro** [comment]
Older runtimes should just version lock your plugin imo - like they would need to version lock cake - if their runtime isn't compatible with netstandard2.0 anywho.

But everything should be netstandard2.0 compatible afaik

**Comment by gep13** [comment]
@ErikSchierboom @git-man @nmbro this should now be taken care of, please let us know if you still have problems.

**Comment by ErikSchierboom** [comment]
@gep13 Can confirm that it is now working!
