### ISSUE TITLE
Would it be possible to use the Cake Contrib Icon for your NuGet Package?

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.FileHelpers#11]
Thanks again for creating this Cake Addin, we really appreciate the effort that you have put in to creating it.  

We, the Cake Team, recently announced a new Cake Contrib Icon, details of which can be found here:

http://cakebuild.net/blog/2017/06/new-cake-contrib-icon

Would you consider changing the nuspec file for your NuGet Package to use this new Cake Contrib Icon?  If so, the recommended URL to use is:

https://cdn.rawgit.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png

Details of the above URL can be found in the repository here:

https://github.com/cake-contrib/graphics

Please let me know if you have any questions.

**Comment by damianh** [comment]
@gep13 I think this project is dead. Time transfer ownership?

**Comment by gep13** [comment]
@damianh I know that @Redth is busy with lots of things, and I am sure that he would appreciate some help with maintenance.

Are you in a position to help out?

**Comment by Redth** [comment]
Yeah a PR to move the icon would be appreciated if anyone wants to grab it.

The point of transferring this to cake-contrib was exactly for this purpose, so others can help out more.

**Comment by gep13** [comment]
@damianh assuming @redth is ok with it, now that this repository is part of cake-contrib, anyone in the Cake Team can merge a PR, and help to get a new release pushed out.
