### ISSUE TITLE
Compatibility with latest cake release 0.22.0

### ISSUE THREAD

**Issue by chris27uk** [cake-contrib/Cake.FileHelpers#15]
Hi, Cake.FileHelpers doesn't appear to be compatible with 0.22.0 build of cake (now in public nuget channel) I've pinned our current builds of cake to 0.21.1 which was the last working build. Is there any current plan to recompile against the new version of Cake.Core?

**Comment by zplan** [comment]
Yes, please update to make the addin compatible. Thx

**Comment by gep13** [comment]
@chris27uk @zplan there is an open PR that @Redth is working on here: https://github.com/cake-contrib/Cake.FileHelpers/pull/14

So hopefully it won't be too much longer.

**Comment by Lakritzator** [comment]
This causes a bit of a deadlock, I need Cake.Http and Cake.FileHelpers in the same cake build script.
Cake.Http needs Cake >= 0.22.0, Cake.FileHelpers <= 0.21.1

There is no workaround, specifying --settings_skipverification=true just make the script terminate with an error (no details).

**Comment by gep13** [comment]
>@Lakritzator said...
This causes a bit of a deadlock,

Why is there a deadlock?  Pin to a specific version of Cake AND specific versions of the addins/tools that you are using?

That way, you should be able to run exactly the same as you were before the release of 0.22.0.

**Comment by Lakritzator** [comment]
Yes, that's why I said "a bit of", not an hard deadlock.
But I do have to go in an figure out the versions, and also I cannot use the new cake features.

Anyway, thanks for the hint.

**Comment by Redth** [comment]
I'm working on an update, think it's almost ready... hold on for it :)

**Comment by rdavisunr** [comment]
Bump - can you make this compatible with Cake 0.26.0.0 ?

**Comment by Redth** [comment]
Yep will be making this all netstandard2.0 shortly...

**Comment by gep13** [comment]
@chris27uk @zplan @Lakritzator @rdavisunr this should now be taken care of, please let us know if you still have problems.
