### ISSUE TITLE
Update Cake.FileHelpers to target Cake v4.0.0

### ISSUE THREAD

**Issue by twenzel** [cake-contrib/Cake.FileHelpers#150]
Support for Cake 4.0

---

[Cake 4.0.0](https://cakebuild.net/blog/2023/11/cake-v4.0.0-released) has been released  🎉

**Comment by janlonsetteig** [comment]
Any ETA on the release of version 7.0.0?

**Comment by augustoproiete** [comment]
@janlonsetteig Cake.FileHelpers v7.0.0 release is out https://www.nuget.org/packages/Cake.FileHelpers/7.0.0
