### ISSUE TITLE
Cake.FileHelpers update reference to Cake.Core version 0.28.0

### ISSUE THREAD

**Issue by tmamedbekov** [cake-contrib/Cake.FileHelpers#26]
Hello,

I am trying to run a build.cake file on my mac, and I am keep getting this error. How can I manually update the references, or is there a plan to update in a near future?

> `The assembly 'Cake.FileHelpers, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' is referencing an older version of Cake.Core (0.26.1). For best compatibility it should target Cake.Core version 0.28.0. Could not load /Users/johnsmith/tmp/project/src/tools/Addins/Cake.Powershell.0.4.6/lib/net46/System.Management.Automation.dll (missing Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35))`

Thank you for you help,

Regards, Tony

**Comment by aivanov-oneinc** [comment]
Looks like #25 pull request can fix an issue

**Comment by tmamedbekov** [comment]
Lets wait for it!

**Comment by gep13** [comment]
@tmamedbekov @aivanov-oneinc this should now be taken care of, please let us know if you still have problems.
