### ISSUE TITLE
Add overloads to pass Encoding

### ISSUE THREAD

**Issue by gitfool** [cake-contrib/Cake.FileHelpers#4]
It's important to have flexibility at the boundaries, especially where you read and write files, so all methods should have overloads for passing [System.Text.Encoding](https://msdn.microsoft.com/en-us/library/system.text.encoding.aspx). This also lets you control Byte Order Mark (BOM) handling.

**Comment by pvoelker** [comment]
Being able to have the encoding specified would be great.  Or at least have a way for the original encoding to be preserved.  My UTF-8 files are getting changed to Western European Windows encoding by 'ReplaceRegexInFiles'.

**Comment by pvoelker** [comment]
I've created a pull request with overloads on the functions for System.Text.Encoding.  The additions were pretty easy to do.  Hopefully the pull request is helpful.

**Comment by Roemer** [comment]
Would definitely be great to have that added.

**Comment by haefele** [comment]
I also would like it very much if we could specify the encoding as well.

**Comment by gureedo** [comment]
+1
