### ISSUE TITLE
Update Cake.FileHelpers add-in to target Cake v2.0.0

### ISSUE THREAD

**Issue by augustoproiete** [cake-contrib/Cake.FileHelpers#79]
[Cake 2.0.0](https://cakebuild.net/blog/2021/11/cake-v2.0.0-released) has been released  🎉

**Comment by twenzel** [comment]
Unfortunately Cake.Receipt itself still not support Cake 2.0 so we have to stick with 0.38.5.

**Comment by augustoproiete** [comment]
Thanks for the PR @twenzel !

ps: Just to double-check: You mean `Cake.Recipe` right?

**Comment by twenzel** [comment]
Yes, I mean `Cake.Recipe`.
