### ISSUE TITLE
[Feature Request] `ReplaceRegexMatchGroupInFiles`

### ISSUE THREAD

**Issue by lonix1** [cake-contrib/Cake.FileHelpers#98]
## Expected Behavior
````cs
// "foo bar baz" >>> "foo BAR baz"
ReplaceRegexMatchGroupInFiles("file.txt", "foo (.*) baz", "BAR", 1, RegexOptions.None);
````

## Current Behavior
````cs
// "foo bar baz" >>> "BAR"
ReplaceRegexInFiles("file.txt", "foo (.*) baz", "BAR", RegexOptions.None);
````

## Possible Solution
current workaround:
````cs
// "foo bar baz" >>> "foo BAR baz"
ReplaceRegexInFiles("file.txt", "foo (.*) baz", "foo BAR baz", RegexOptions.None);
````

But that is very ugly for complex/long regexes.

The form shown above in "expected behavior" is better. The signature should be similar to that of `FindRegexMatchGroupInFile` which takes a regex group index.

## Steps to Reproduce (for bugs)
n/a

## Context
n/a

## Your Environment
* Addin version used: 5.0.0
* Cake Version used: 2.2.0
* Operating System: linux

**Comment by nils-a** [comment]
If you go down the regex road, wouldn't it be easier to simply use what is at hand, and use

```cs
ReplaceRegexInFiles("file.txt", "(foo )(.*)( baz)", "$1BAR$3", RegexOptions.None);
```

**Comment by lonix1** [comment]
Problem was dotnet's underlying regex engine, not cake itself.
